//! Real Groth16 proving and verification (arkworks, BLS12-381 curve).
//!
//! This module provides a compact, fully documented **demo circuit** that
//! mirrors the shielded-transfer flow:
//!
//! | role        | value                              |
//! |-------------|------------------------------------|
//! | public      | `commitment`, `nullifier`          |
//! | private     | `secret`, `recipient`              |
//! | constraint 1| `secret · secret = s_sq`          |
//! | constraint 2| `s_sq + recipient = commitment`   |
//! | constraint 3| `secret · recipient = nullifier`  |
//!
//! It proves knowledge of a note secret whose committed value matches an
//! on-chain deposit, with a spend-guard nullifier. Production circuits should
//! additionally bind the withdrawal `recipient` and `amount` as public inputs
//! (front-running protection) and use a Poseidon/Merkle membership circuit
//! (see `circuit.rs`).
//!
//! The on-chain counterpart (`stellar-privacy-contract::g16`) verifies exactly
//! the artifacts produced here using Stellar's native BLS12-381 host
//! functions. Fixtures are generated by `examples/gen_groth16_fixture.rs` and
//! committed under `packages/contract/test_snapshots/groth16/` so contract
//! tests prove a real proof end-to-end.

use ark_bls12_381::{Bls12_381, Fr};
use ark_groth16::{Groth16, Proof, ProvingKey, VerifyingKey};
use ark_relations::lc;
use ark_relations::r1cs::{ConstraintSynthesizer, ConstraintSystemRef, SynthesisError, Variable};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_snark::SNARK;
use rand::rngs::StdRng;
use rand::{CryptoRng, RngCore, SeedableRng};
use serde::{Deserialize, Serialize};

/// Uncompressed G1 point serialization size (x ‖ y, 48 bytes each).
pub const G1_UNCOMPRESSED_BYTES: usize = 96;
/// Uncompressed G2 point serialization size (x_c1 ‖ x_c0 ‖ y_c1 ‖ y_c0).
pub const G2_UNCOMPRESSED_BYTES: usize = 192;
/// Scalar (`Fr`) serialization size.
pub const FR_BYTES: usize = 32;

/// Identifier of the demo circuit, recorded inside generated fixtures.
pub const DEMO_CIRCUIT_ID: &str = "shielded-transfer-demo-v1";

// ---------------------------------------------------------------------------
// Circuit
// ---------------------------------------------------------------------------

/// A Groth16 circuit proving knowledge of a note secret:
///
/// `commitment = secret² + recipient`, `nullifier = secret · recipient`.
///
/// `None` fields are used during trusted setup (witness unknown); `Some` is
/// required when generating a proof.
#[derive(Clone, Debug)]
pub struct ShieldedTransferCircuit {
    pub secret: Option<Fr>,
    pub recipient: Option<Fr>,
    pub commitment: Option<Fr>,
    pub nullifier: Option<Fr>,
}

impl ShieldedTransferCircuit {
    /// Circuit instantiated without a witness (for trusted setup).
    pub fn blank() -> Self {
        Self {
            secret: None,
            recipient: None,
            commitment: None,
            nullifier: None,
        }
    }
}

impl ConstraintSynthesizer<Fr> for ShieldedTransferCircuit {
    fn generate_constraints(self, cs: ConstraintSystemRef<Fr>) -> Result<(), SynthesisError> {
        let secret =
            cs.new_witness_variable(|| self.secret.ok_or(SynthesisError::AssignmentMissing))?;
        let recipient =
            cs.new_witness_variable(|| self.recipient.ok_or(SynthesisError::AssignmentMissing))?;
        let commitment =
            cs.new_input_variable(|| self.commitment.ok_or(SynthesisError::AssignmentMissing))?;
        let nullifier =
            cs.new_input_variable(|| self.nullifier.ok_or(SynthesisError::AssignmentMissing))?;

        // secret * secret = s_sq
        let s_sq = cs.new_witness_variable(|| {
            self.secret
                .map(|s| s * s)
                .ok_or(SynthesisError::AssignmentMissing)
        })?;
        cs.enforce_constraint(lc!() + secret, lc!() + secret, lc!() + s_sq)?;

        // (s_sq + recipient) * 1 = commitment
        cs.enforce_constraint(
            lc!() + s_sq + recipient,
            lc!() + Variable::One,
            lc!() + commitment,
        )?;

        // secret * recipient = nullifier
        cs.enforce_constraint(lc!() + secret, lc!() + recipient, lc!() + nullifier)?;

        Ok(())
    }
}

/// Demo witness values (documented; all below the field modulus).
#[derive(Clone, Copy, Debug)]
pub struct DemoValues {
    pub secret: Fr,
    pub recipient: Fr,
    pub commitment: Fr,
    pub nullifier: Fr,
}

/// The fixed demo witness: `secret = 12345`, `recipient = 67890`.
pub fn demo_values() -> DemoValues {
    let secret = Fr::from(12_345u64);
    let recipient = Fr::from(67_890u64);
    let s_sq = secret * secret;
    DemoValues {
        secret,
        recipient,
        commitment: s_sq + recipient,
        nullifier: secret * recipient,
    }
}

// ---------------------------------------------------------------------------
// Setup / prove / verify
// ---------------------------------------------------------------------------

/// Runs the Groth16 trusted setup for the demo circuit.
pub fn setup(
    rng: &mut (impl RngCore + CryptoRng),
) -> (ProvingKey<Bls12_381>, VerifyingKey<Bls12_381>) {
    Groth16::<Bls12_381>::circuit_specific_setup(ShieldedTransferCircuit::blank(), rng)
        .expect("failed to generate Groth16 parameters")
}

/// Generates a Groth16 proof for the demo witness.
pub fn prove(
    rng: &mut (impl RngCore + CryptoRng),
    pk: &ProvingKey<Bls12_381>,
    values: &DemoValues,
) -> Proof<Bls12_381> {
    let circuit = ShieldedTransferCircuit {
        secret: Some(values.secret),
        recipient: Some(values.recipient),
        commitment: Some(values.commitment),
        nullifier: Some(values.nullifier),
    };
    Groth16::<Bls12_381>::prove(pk, circuit, rng).expect("failed to generate proof")
}

/// Off-chain reference verification (arkworks).
pub fn verify(
    vk: &VerifyingKey<Bls12_381>,
    public_inputs: &[Fr],
    proof: &Proof<Bls12_381>,
) -> bool {
    Groth16::<Bls12_381>::verify(vk, public_inputs, proof).unwrap_or(false)
}

// ---------------------------------------------------------------------------
// Fixture (de)serialization — the exact format the contract verifier consumes
// ---------------------------------------------------------------------------

/// Full serializable fixture: verifying key + proof + public inputs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Groth16Fixture {
    pub circuit: String,
    pub vk: Groth16VkJson,
    pub proof: Groth16ProofJson,
    pub public_inputs: Vec<String>,
}

/// Serialized verifying key. Points are **uncompressed** hex:
/// 96 bytes for G1, 192 bytes for G2 (SDK host-function encoding).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Groth16VkJson {
    pub alpha_g1: String,
    pub beta_g2: String,
    pub gamma_g2: String,
    pub delta_g2: String,
    pub gamma_abc_g1: Vec<String>,
}

/// Serialized proof. Points are **uncompressed** hex.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Groth16ProofJson {
    pub a: String,
    pub b: String,
    pub c: String,
}

fn serialize_hex<T: CanonicalSerialize>(value: &T, uncompressed: bool) -> String {
    let mut buf = Vec::new();
    if uncompressed {
        value
            .serialize_uncompressed(&mut buf)
            .expect("serialize failed");
    } else {
        value
            .serialize_compressed(&mut buf)
            .expect("serialize failed");
    }
    hex::encode(buf)
}

/// Serializes a scalar as a **big-endian** 32-byte hex string.
///
/// arkworks writes field elements little-endian; the Soroban host reads
/// scalars as big-endian integers (`U256::from_be_bytes`), so the fixture
/// stores them big-endian. The contract verifier's `Fr::from_bytes` then
/// reproduces the exact scalar.
fn serialize_fr_be(value: &Fr) -> String {
    let mut buf = Vec::new();
    value
        .serialize_compressed(&mut buf)
        .expect("serialize failed");
    buf.reverse();
    hex::encode(buf)
}

/// Builds a fixture from a valid (vk, proof, public inputs) triple.
pub fn build_fixture(
    vk: &VerifyingKey<Bls12_381>,
    proof: &Proof<Bls12_381>,
    public_inputs: &[Fr],
) -> Groth16Fixture {
    Groth16Fixture {
        circuit: DEMO_CIRCUIT_ID.to_string(),
        vk: Groth16VkJson {
            alpha_g1: serialize_hex(&vk.alpha_g1, true),
            beta_g2: serialize_hex(&vk.beta_g2, true),
            gamma_g2: serialize_hex(&vk.gamma_g2, true),
            delta_g2: serialize_hex(&vk.delta_g2, true),
            gamma_abc_g1: vk
                .gamma_abc_g1
                .iter()
                .map(|p| serialize_hex(p, true))
                .collect(),
        },
        proof: Groth16ProofJson {
            a: serialize_hex(&proof.a, true),
            b: serialize_hex(&proof.b, true),
            c: serialize_hex(&proof.c, true),
        },
        public_inputs: public_inputs.iter().map(serialize_fr_be).collect(),
    }
}

fn deserialize_hex<T: CanonicalDeserialize>(s: &str, uncompressed: bool) -> Result<T, String> {
    let bytes = hex::decode(s).map_err(|e| format!("hex decode: {e}"))?;
    if uncompressed {
        T::deserialize_uncompressed(&bytes[..]).map_err(|e| format!("deserialize: {e}"))
    } else {
        T::deserialize_compressed(&bytes[..]).map_err(|e| format!("deserialize: {e}"))
    }
}

/// Parsed fixture artifacts: verifying key, proof, and public inputs.
pub type ParsedGroth16 = (VerifyingKey<Bls12_381>, Proof<Bls12_381>, Vec<Fr>);

/// Parses a fixture back into arkworks artifacts for verification.
pub fn parse_fixture(fixture: &Groth16Fixture) -> Result<ParsedGroth16, String> {
    let alpha_g1: ark_bls12_381::G1Affine = deserialize_hex(&fixture.vk.alpha_g1, true)?;
    let beta_g2: ark_bls12_381::G2Affine = deserialize_hex(&fixture.vk.beta_g2, true)?;
    let gamma_g2: ark_bls12_381::G2Affine = deserialize_hex(&fixture.vk.gamma_g2, true)?;
    let delta_g2: ark_bls12_381::G2Affine = deserialize_hex(&fixture.vk.delta_g2, true)?;
    let gamma_abc_g1 = fixture
        .vk
        .gamma_abc_g1
        .iter()
        .map(|s| deserialize_hex::<ark_bls12_381::G1Affine>(s, true))
        .collect::<Result<Vec<_>, _>>()?;

    let vk = VerifyingKey {
        alpha_g1,
        beta_g2,
        gamma_g2,
        delta_g2,
        gamma_abc_g1,
    };

    let a: ark_bls12_381::G1Affine = deserialize_hex(&fixture.proof.a, true)?;
    let b: ark_bls12_381::G2Affine = deserialize_hex(&fixture.proof.b, true)?;
    let c: ark_bls12_381::G1Affine = deserialize_hex(&fixture.proof.c, true)?;
    let proof = Proof { a, b, c };

    let public_inputs = fixture
        .public_inputs
        .iter()
        .map(|s| {
            // Fixture stores scalars big-endian; arkworks parses little-endian.
            let mut bytes = hex::decode(s).map_err(|e| format!("hex decode: {e}"))?;
            bytes.reverse();
            Fr::deserialize_compressed(&bytes[..]).map_err(|e| format!("deserialize: {e}"))
        })
        .collect::<Result<Vec<_>, _>>()?;

    Ok((vk, proof, public_inputs))
}

/// Deterministic RNG for reproducible setups/fixtures.
pub fn deterministic_rng(seed: u64) -> StdRng {
    StdRng::seed_from_u64(seed)
}

#[cfg(test)]
mod tests {
    use super::*;

    const COMMITTED_FIXTURE: &str =
        include_str!("../../contract/test_snapshots/groth16/fixture.json");

    #[test]
    fn test_groth16_end_to_end() {
        let values = demo_values();
        let mut rng = deterministic_rng(0xC0FFEE);
        let (pk, vk) = setup(&mut rng);
        let proof = prove(&mut rng, &pk, &values);

        let public_inputs = vec![values.commitment, values.nullifier];
        assert!(verify(&vk, &public_inputs, &proof));

        // Tampering with any proof element must fail verification.
        let mut tampered = proof.clone();
        tampered.c = -tampered.c;
        assert!(!verify(&vk, &public_inputs, &tampered));

        // Wrong public inputs must fail.
        assert!(!verify(&vk, &[values.commitment + Fr::from(1u64)], &proof));
    }

    #[test]
    fn test_demo_values_consistent() {
        let v = demo_values();
        // commitment = secret² + recipient
        assert_eq!(v.commitment, v.secret * v.secret + v.recipient);
        // nullifier = secret * recipient
        assert_eq!(v.nullifier, v.secret * v.recipient);
        assert_eq!(v.commitment, Fr::from(152_466_915u64));
        assert_eq!(v.nullifier, Fr::from(838_102_050u64));
    }

    #[test]
    fn test_fixture_roundtrip() {
        let values = demo_values();
        let mut rng = deterministic_rng(42);
        let (pk, vk) = setup(&mut rng);
        let proof = prove(&mut rng, &pk, &values);
        let public_inputs = vec![values.commitment, values.nullifier];

        let fixture = build_fixture(&vk, &proof, &public_inputs);
        let json = serde_json::to_string_pretty(&fixture).unwrap();
        let parsed: Groth16Fixture = serde_json::from_str(&json).unwrap();
        let (vk2, proof2, inputs2) = parse_fixture(&parsed).unwrap();

        assert!(verify(&vk2, &inputs2, &proof2));
        assert_eq!(inputs2, public_inputs);
        assert_eq!(fixture.circuit, DEMO_CIRCUIT_ID);
    }
    /// Guards the committed contract fixture: it must be a *valid* Groth16
    /// proof for its own verifying key (arkworks reference verification) AND
    /// correspond to the current demo circuit values, so a stale fixture (e.g.
    /// generated from an older circuit) fails CI.
    #[test]
    fn test_committed_fixture_is_valid() {
        let fixture: Groth16Fixture =
            serde_json::from_str(COMMITTED_FIXTURE).expect("fixture must parse");
        assert_eq!(fixture.circuit, DEMO_CIRCUIT_ID);

        // The fixture's public inputs must match the documented demo witness.
        let values = demo_values();
        assert_eq!(
            fixture.public_inputs,
            vec![
                serialize_fr_be(&values.commitment),
                serialize_fr_be(&values.nullifier)
            ],
            "fixture public inputs must match demo_values()"
        );

        let (vk, proof, public_inputs) = parse_fixture(&fixture).unwrap();
        assert!(
            verify(&vk, &public_inputs, &proof),
            "committed fixture must verify"
        );

        // And it must reject tampering.
        let mut tampered = proof.clone();
        tampered.a = -tampered.a;
        assert!(!verify(&vk, &public_inputs, &tampered));
    }

    /// Replicates the on-chain verification algorithm (`contract::g16`) with
    /// arkworks: parse the committed fixture, compute the public-input MSM,
    /// and check the pairing product equals the identity. Passing this test
    /// proves the contract's equation is exactly ark's reference equation.
    #[test]
    fn test_manual_pairing_verification_matches_reference() {
        use ark_bls12_381::{Bls12_381, Fq12, G1Projective, G2Projective};
        use ark_ec::pairing::Pairing;
        use ark_ec::scalar_mul::variable_base::VariableBaseMSM;
        use ark_ff::Field;
        use ark_std::iter::once;

        let fixture: Groth16Fixture =
            serde_json::from_str(COMMITTED_FIXTURE).expect("fixture must parse");
        let (vk, proof, public_inputs) = parse_fixture(&fixture).unwrap();
        assert!(verify(&vk, &public_inputs, &proof));

        let alpha: G1Projective = vk.alpha_g1.into();
        let beta: G2Projective = vk.beta_g2.into();
        let gamma: G2Projective = vk.gamma_g2.into();
        let delta: G2Projective = vk.delta_g2.into();
        let a: G1Projective = proof.a.into();
        let b: G2Projective = proof.b.into();
        let c: G1Projective = proof.c.into();

        // msm = gamma_abc[0] + Σᵢ pub[i]·gamma_abc[i+1]
        let coeffs: Vec<Fr> = once(Fr::ONE).chain(public_inputs.iter().copied()).collect();
        let msm = G1Projective::msm(&vk.gamma_abc_g1, &coeffs).expect("msm");

        let lhs = Bls12_381::multi_pairing([-a, alpha, msm, c], [b, beta, gamma, delta]);
        assert_eq!(
            lhs.0,
            Fq12::ONE,
            "pairing product must be identity (contract equation)"
        );
    }
}
